[package]
name = "beepy-games"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beepy-display = "0.1.1"
embedded-graphics = "0.8.1"
evdev = "0.12.1"
rand = "0.8.5"
tinybmp = "0.5.0"
